version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      eslint:
        patterns:
          - "eslint"
          - "@eslint/*"
          - "eslint-*"
          - "@typescript-eslint/*"
          - "typescript-eslint"
      vite:
        patterns:
          - "vite"
          - "@vitejs/*"
          - "vitest"
          - "@vitest/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
