export interface Character {
  id: string
  name: string | null
  origin: string | null
  origin_region: string | null
  is_likely_character: boolean | null
  status: string | null
  birth: string | null
  blood_type: string | null
  blood_type_group: string | null
  bounties: string | null
  bounty: number | null
  age: number | null
  scraping_status: string | null
  scraping_note: string | null
  birth_date: string | null
  chapter_list: number[] | null
  volume_list: number[] | null
  appearance_count: number | null
  volume_appearance_count: number | null
  first_appearance: number | null
  last_appearance: number | null
  arc_list: string[] | null
  saga_list: string[] | null
  cover_volume_list: number[] | null
  cover_appearance_count: number | null
  haki_observation: boolean | null
  haki_armament: boolean | null
  haki_conqueror: boolean | null
  bio: string | null
}
