/**
 * Embed renderers for all insight charts.
 *
 * Each chart is accessible at: /#/embed/insights/<slug>
 * Permalink on the main page:  /#/analytics/insights#<slug>
 *
 * ┌─────┬────────────────────────────────────────┬────────────────────────────┬────────────────────────────┐
 * │ #   │ Title                                  │ Slug                       │ Interactive Filters        │
 * ├─────┼────────────────────────────────────────┼────────────────────────────┼────────────────────────────┤
 * │ 1   │ Cast Complexity Over Time              │ cast-complexity            │ —                          │
 * │ 2   │ Bounty vs Appearance Count             │ bounty-vs-appearance       │ SHP toggle                 │
 * │ 3   │ Bounty Jumps                           │ bounty-jumps               │ Sortable table             │
 * │ 4   │ Bounty Tier Distribution by Region     │ region-bounty-tier         │ Count / %                  │
 * │ 5   │ Most "Loyal" Characters                │ most-loyal                 │ —                          │
 * │ 6   │ One-Arc Wonders vs Recurring Cast      │ arc-count-distribution     │ —                          │
 * │ 6b  │ One-Saga Wonders vs Recurring Cast     │ saga-count-distribution    │ —                          │
 * │ 7   │ Characters per Arc (New vs Returning)  │ arc-intro-rate             │ Both / New / Returning     │
 * │ 7b  │ Characters per Saga (New vs Returning) │ saga-intro-rate            │ Both / New / Returning     │
 * │ 8   │ Longest Disappearances                 │ gap-analysis               │ —                          │
 * │ 9   │ Arc Length Trend                       │ arc-length-trend           │ —                          │
 * │ 10  │ Total Pages per Arc                    │ pages-per-arc              │ —                          │
 * │ 11  │ Saga Pacing Comparison                 │ saga-pacing                │ —                          │
 * │ 12  │ Chapters per Year                      │ yearly-releases            │ —                          │
 * │ 13  │ Blood Type: One Piece vs Japan         │ blood-type-comparison      │ —                          │
 * │ 14  │ Birthday Calendar by Month             │ birthday-distribution      │ —                          │
 * │ 15  │ Origin Region Bubble Chart             │ origin-regions             │ —                          │
 * │ 16  │ Age Distribution by Status             │ age-distribution           │ —                          │
 * │ 17  │ Cover Page Stars                       │ cover-stars                │ —                          │
 * │ 18  │ Cover vs Main Story Appearances        │ cover-vs-main              │ —                          │
 * │ 19  │ Character Cast Size per Arc            │ arc-density                │ —                          │
 * │ 20  │ The Completeness Gap                   │ data-completeness          │ —                          │
 * │ 21  │ Top Characters per Saga                │ top-characters-per-saga    │ SHP 3-way + Count / %      │
 * │ 22  │ Top Characters per Arc                 │ top-characters-per-arc     │ SHP 3-way + Count / %      │
 * │ 23  │ Largest Crews & Organizations          │ largest-groups             │ —                          │
 * │ 24  │ Crew Loyalty vs Turnover               │ crew-loyalty               │ —                          │
 * └─────┴────────────────────────────────────────┴────────────────────────────┴────────────────────────────┘
 *
 * To add a new embed:
 * 1. Add the compute function call in the `insights` useMemo block
 * 2. Create an Embed* component that renders the chart with EmbedFooter
 * 3. Add the slug → component mapping in `chartMap`
 * 4. Add chartId and embedPath props to the ChartCard on OnePieceInsightsPage
 *
 * Auto-generated by: npx tsx src/scripts/updateEmbedChartIndex.ts
 */
import { useMemo, useState } from 'react'
import { useParams, Link } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  ScatterChart,
  Scatter,
  AreaChart,
  Area,
  Line,
  Legend,
  Cell,
  PieChart,
  Pie,
} from 'recharts'
import {
  fetchInsightsRawData,
  computeChapterComplexity,
  computeBountyVsAppearance,
  computeTopBountyJumps,
  computeRegionBountyTier,
  BOUNTY_TIER_LABELS,
  computeMostLoyal,
  computeArcCountDistribution,
  computeSagaCountDistribution,
  computeArcIntroRate,
  computeSagaIntroRate,
  computeLongestGaps,
  computeArcLengths,
  computePagesPerArc,
  computeSagaPacing,
  computeYearlyReleases,
  computeBloodTypeComparison,
  computeBirthdayDistribution,
  computeRegionCounts,
  computeAgeDistribution,
  computeCoverStars,
  computeCoverVsMain,
  computeArcDensity,
  computeCompleteness,
  computeTopCharactersPerSaga,
  computeTopCharactersPerArc,
  computeLargestGroups,
  computeCrewLoyalty,
  type BountyJump,
} from '../services/analyticsService'
import { STRAW_HAT_IDS } from '../constants/characters'
import SortableTable, { Column } from '../components/common/SortableTable'

const formatBounty = (value: number) => {
  if (value >= 1_000_000_000) return `${(value / 1_000_000_000).toFixed(1)}B`
  if (value >= 1_000_000) return `${(value / 1_000_000).toFixed(0)}M`
  if (value >= 1_000) return `${(value / 1_000).toFixed(0)}K`
  return value.toLocaleString()
}

const SAGA_COLORS = [
  '#3b82f6',
  '#8b5cf6',
  '#ec4899',
  '#f59e0b',
  '#10b981',
  '#ef4444',
  '#06b6d4',
  '#f97316',
  '#84cc16',
  '#6366f1',
  '#14b8a6',
  '#e11d48',
]

const bountyJumpColumns: Column<BountyJump>[] = [
  {
    key: 'name',
    label: 'Character',
    sortValue: (row) => row.name,
    render: (row) => (
      <Link
        to={`/characters/${row.id}`}
        target="_blank"
        className="text-blue-600 hover:text-blue-800 hover:underline font-medium"
      >
        {row.name}
      </Link>
    ),
  },
  {
    key: 'firstBounty',
    label: 'First Bounty',
    sortValue: (row) => row.firstBounty,
    render: (row) => (
      <span className="text-gray-600">{formatBounty(row.firstBounty)}</span>
    ),
  },
  {
    key: 'lastBounty',
    label: 'Last Bounty',
    sortValue: (row) => row.lastBounty,
    render: (row) => (
      <span className="font-medium text-amber-600">
        {formatBounty(row.lastBounty)}
      </span>
    ),
  },
  {
    key: 'jump',
    label: 'Jump',
    sortValue: (row) => row.jump,
    render: (row) => (
      <span
        className={`font-medium ${row.jump >= 0 ? 'text-emerald-600' : 'text-red-600'}`}
      >
        {row.jump >= 0 ? '+' : '-'}
        {formatBounty(Math.abs(row.jump))}
      </span>
    ),
  },
  {
    key: 'multiplier',
    label: 'Multiplier',
    sortValue: (row) => row.multiplier,
    render: (row) => (
      <span
        className={`font-bold ${row.multiplier >= 1 ? 'text-purple-600' : 'text-red-600'}`}
      >
        {row.multiplier}x
      </span>
    ),
  },
]

function EmbedInsightPage() {
  const { chartId } = useParams<{ chartId: string }>()

  const { data: raw, isLoading } = useQuery({
    queryKey: ['insights-raw-data'],
    queryFn: fetchInsightsRawData,
    staleTime: 10 * 60 * 1000,
  })

  const insights = useMemo(() => {
    if (!raw) return null
    const { characters, arcs, sagas, chapters } = raw
    return {
      chapterComplexity: computeChapterComplexity(
        characters,
        arcs,
        chapters.length > 0 ? Math.max(...chapters.map((c) => c.number)) : 0
      ),
      bountyVsAppearance: computeBountyVsAppearance(characters),
      topBountyJumps: computeTopBountyJumps(characters),
      regionBountyTier: computeRegionBountyTier(characters),
      mostLoyal: computeMostLoyal(characters),
      arcCountDistribution: computeArcCountDistribution(characters, arcs, 2),
      sagaCountDistribution: computeSagaCountDistribution(characters, sagas, 2),
      arcIntroRate: computeArcIntroRate(characters, arcs),
      sagaIntroRate: computeSagaIntroRate(characters, sagas),
      longestGaps: computeLongestGaps(characters),
      arcLengths: computeArcLengths(arcs),
      pagesPerArc: computePagesPerArc(arcs, chapters),
      sagaPacing: computeSagaPacing(sagas, arcs, characters, chapters),
      yearlyReleases: computeYearlyReleases(chapters),
      bloodType: computeBloodTypeComparison(characters),
      birthdays: computeBirthdayDistribution(characters),
      regionCounts: computeRegionCounts(characters),
      ageDistribution: computeAgeDistribution(characters),
      coverStars: computeCoverStars(characters),
      coverVsMain: computeCoverVsMain(characters),
      arcDensity: computeArcDensity(characters, arcs),
      completeness: computeCompleteness(characters),
      topCharactersPerSaga: computeTopCharactersPerSaga(characters, sagas, 31),
      topCharactersPerArc: computeTopCharactersPerArc(characters, arcs, 31),
      largestGroups: computeLargestGroups(raw.affiliations),
      crewLoyalty: computeCrewLoyalty(raw.affiliations),
    }
  }, [raw])

  if (isLoading) {
    return (
      <div className="flex justify-center items-center p-8">
        <div className="animate-spin rounded-full h-10 w-10 border-b-2 border-blue-600"></div>
      </div>
    )
  }

  if (!insights) return null

  const chartMap: Record<string, React.ReactNode> = {
    'cast-complexity': (
      <EmbedCastComplexity data={insights.chapterComplexity} />
    ),
    'bounty-vs-appearance': (
      <EmbedBountyVsAppearance data={insights.bountyVsAppearance} />
    ),
    'bounty-jumps': <EmbedBountyJumps data={insights.topBountyJumps} />,
    'region-bounty-tier': (
      <EmbedRegionBountyTier data={insights.regionBountyTier.slice(0, 15)} />
    ),
    'most-loyal': <EmbedMostLoyal data={insights.mostLoyal} />,
    'arc-count-distribution': (
      <EmbedArcCountDistribution data={insights.arcCountDistribution} />
    ),
    'saga-count-distribution': (
      <EmbedSagaCountDistribution data={insights.sagaCountDistribution} />
    ),
    'arc-intro-rate': <EmbedArcIntroRate data={insights.arcIntroRate} />,
    'saga-intro-rate': <EmbedSagaIntroRate data={insights.sagaIntroRate} />,
    'gap-analysis': <EmbedGapAnalysis data={insights.longestGaps} />,
    'arc-length-trend': <EmbedArcLengthTrend data={insights.arcLengths} />,
    'pages-per-arc': <EmbedPagesPerArc data={insights.pagesPerArc} />,
    'saga-pacing': <EmbedSagaPacing data={insights.sagaPacing} />,
    'yearly-releases': <EmbedYearlyReleases data={insights.yearlyReleases} />,
    'blood-type-comparison': (
      <EmbedBloodTypeComparison data={insights.bloodType} />
    ),
    'birthday-distribution': (
      <EmbedBirthdayDistribution data={insights.birthdays} />
    ),
    'origin-regions': <EmbedOriginRegions data={insights.regionCounts} />,
    'age-distribution': (
      <EmbedAgeDistribution data={insights.ageDistribution} />
    ),
    'cover-stars': <EmbedCoverStars data={insights.coverStars} />,
    'cover-vs-main': <EmbedCoverVsMain data={insights.coverVsMain} />,
    'arc-density': <EmbedArcDensity data={insights.arcDensity} />,
    'data-completeness': <EmbedDataCompleteness data={insights.completeness} />,
    'top-characters-per-saga': (
      <EmbedTopCharactersPerSaga data={insights.topCharactersPerSaga} />
    ),
    'top-characters-per-arc': (
      <EmbedTopCharactersPerArc data={insights.topCharactersPerArc} />
    ),
    'largest-groups': <EmbedLargestGroups data={insights.largestGroups} />,
    'crew-loyalty': <EmbedCrewLoyalty data={insights.crewLoyalty} />,
  }

  const chart = chartId ? chartMap[chartId] : null

  if (!chart) {
    return (
      <div className="p-8 text-center text-gray-500">
        Chart not found: {chartId}
      </div>
    )
  }

  return <>{chart}</>
}

// ── #1 Cast Complexity ──────────────────────────────────────────────────────

function EmbedCastComplexity({
  data,
}: {
  data: ReturnType<typeof computeChapterComplexity>
}) {
  return (
    <div className="p-4 font-sans">
      <h2 className="text-lg font-semibold text-gray-900 mb-3">
        Cast Complexity Over Time
      </h2>
      <ResponsiveContainer width="100%" height={350}>
        <AreaChart
          data={data}
          margin={{ top: 5, right: 30, left: 20, bottom: 5 }}
        >
          <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
          <XAxis
            dataKey="chapter"
            type="number"
            domain={[1, 'dataMax']}
            ticks={[1, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100]}
            tick={{ fontSize: 11 }}
            stroke="#6b7280"
            label={{
              value: 'Chapter',
              position: 'insideBottom',
              offset: -5,
              style: { fontSize: 11, fill: '#6b7280' },
            }}
          />
          <YAxis tick={{ fontSize: 11 }} stroke="#6b7280" />
          <Tooltip
            labelFormatter={(label: number) => {
              const d = data.find((p) => p.chapter === label)
              return d ? `Chapter ${label} (${d.arc})` : `Chapter ${label}`
            }}
            formatter={(value: number, name: string) => [
              name === 'Characters in Chapter'
                ? `${value} characters`
                : `${value} avg`,
              name,
            ]}
          />
          <Legend />
          <Area
            type="monotone"
            dataKey="characters"
            fill="#dbeafe"
            stroke="#93c5fd"
            strokeWidth={1}
            fillOpacity={0.4}
            name="Characters in Chapter"
          />
          <Line
            type="monotone"
            dataKey="rollingAvg"
            stroke="#2563eb"
            strokeWidth={2}
            dot={false}
            name="Rolling Average (20 ch.)"
          />
          <Line
            type="linear"
            dataKey="trend"
            stroke="#ef4444"
            strokeWidth={2}
            strokeDasharray="8 4"
            dot={false}
            name="Trendline"
          />
        </AreaChart>
      </ResponsiveContainer>
      <EmbedFooter />
    </div>
  )
}

// ── #2 Bounty vs Appearance ─────────────────────────────────────────────────

function EmbedBountyVsAppearance({
  data,
}: {
  data: ReturnType<typeof computeBountyVsAppearance>
}) {
  const [hideStrawHats, setHideStrawHats] = useState(true)
  const filtered = hideStrawHats
    ? data.filter((d) => !STRAW_HAT_IDS.has(d.id))
    : data

  return (
    <div className="p-4 font-sans">
      <div className="flex items-center justify-between mb-3">
        <h2 className="text-lg font-semibold text-gray-900">
          Bounty vs Appearance Count
        </h2>
        <button
          onClick={() => setHideStrawHats((v) => !v)}
          className={`px-3 py-1.5 text-xs rounded-md transition-colors ${
            hideStrawHats
              ? 'bg-blue-600 text-white'
              : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
          }`}
        >
          {hideStrawHats ? 'SHP Hidden' : 'Hide SHP'}
        </button>
      </div>
      <ResponsiveContainer width="100%" height={400}>
        <ScatterChart margin={{ top: 10, right: 30, left: 20, bottom: 10 }}>
          <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
          <XAxis
            type="number"
            dataKey="appearances"
            name="Appearances"
            tick={{ fontSize: 11 }}
            stroke="#6b7280"
          />
          <YAxis
            type="number"
            dataKey="bounty"
            name="Bounty"
            tickFormatter={formatBounty}
            tick={{ fontSize: 11 }}
            stroke="#6b7280"
          />
          <Tooltip
            content={({ payload }) => {
              if (!payload || payload.length === 0) return null
              const d = payload[0]?.payload as
                | {
                    name?: string
                    bounty?: number
                    appearances?: number
                    status?: string
                  }
                | undefined
              if (!d) return null
              return (
                <div className="bg-white border border-gray-200 rounded-lg px-3 py-2 shadow-lg text-sm">
                  <p className="font-semibold text-gray-900">{d.name}</p>
                  <p className="text-gray-600">
                    Bounty:{' '}
                    <span className="font-medium text-amber-600">
                      {formatBounty(d.bounty || 0)}
                    </span>
                  </p>
                  <p className="text-gray-600">
                    Appearances:{' '}
                    <span className="font-medium text-blue-600">
                      {d.appearances}
                    </span>
                  </p>
                  <p className="text-gray-600">
                    Status:{' '}
                    <span
                      className={
                        d.status === 'Alive'
                          ? 'text-emerald-600'
                          : 'text-red-600'
                      }
                    >
                      {d.status}
                    </span>
                  </p>
                </div>
              )
            }}
          />
          <Scatter data={filtered} fill="#6366f1" fillOpacity={0.6}>
            {filtered.map((entry, i) => (
              <Cell
                key={i}
                fill={entry.status === 'Alive' ? '#10b981' : '#ef4444'}
              />
            ))}
          </Scatter>
        </ScatterChart>
      </ResponsiveContainer>
      <div className="flex items-center gap-4 mt-2 text-xs text-gray-500">
        <span className="flex items-center gap-1">
          <span className="w-3 h-3 rounded-full bg-emerald-500 inline-block"></span>{' '}
          Alive
        </span>
        <span className="flex items-center gap-1">
          <span className="w-3 h-3 rounded-full bg-red-500 inline-block"></span>{' '}
          Deceased / Unknown
        </span>
      </div>
      <EmbedFooter />
    </div>
  )
}

// ── #3 Bounty Jumps ─────────────────────────────────────────────────────────

function EmbedBountyJumps({ data }: { data: BountyJump[] }) {
  return (
    <div className="p-4 font-sans">
      <h2 className="text-lg font-semibold text-gray-900 mb-3">Bounty Jumps</h2>
      {data.length > 0 ? (
        <SortableTable<BountyJump>
          columns={bountyJumpColumns}
          data={data}
          defaultSortField="jump"
          defaultSortDirection="desc"
          rowKey={(row) => row.id}
          maxHeight="500px"
        />
      ) : (
        <p className="text-gray-500 text-center py-8">
          No bounty history data available
        </p>
      )}
      <EmbedFooter />
    </div>
  )
}

// ── #4 Region Bounty Tier ───────────────────────────────────────────────────

function EmbedRegionBountyTier({
  data,
}: {
  data: ReturnType<typeof computeRegionBountyTier>
}) {
  const [showPct, setShowPct] = useState(true)

  const pctData = useMemo(
    () =>
      data.map((r) => {
        const row: Record<string, string | number> = { region: r.region }
        if (r.total <= 0) {
          for (const { label } of BOUNTY_TIER_LABELS) row[label] = 0
          return row
        }
        const raw: { label: string; pct: number }[] = BOUNTY_TIER_LABELS.map(
          ({ label }) => {
            const v = (r[label] as number) || 0
            return { label, pct: Math.round((v / r.total) * 1000) / 10 }
          }
        )
        const sum = raw.reduce((s, t) => s + t.pct, 0)
        if (sum !== 100) {
          const largest = raw.reduce((a, b) => (b.pct > a.pct ? b : a))
          largest.pct = Math.round((largest.pct + (100 - sum)) * 10) / 10
        }
        for (const t of raw) row[t.label] = t.pct
        return row
      }),
    [data]
  )

  return (
    <div className="p-4 font-sans">
      <div className="flex items-center justify-between mb-3">
        <h2 className="text-lg font-semibold text-gray-900">
          Bounty Tier Distribution by Region
        </h2>
        <button
          onClick={() => setShowPct((v) => !v)}
          className="px-3 py-1 text-xs font-medium rounded-lg border border-gray-300 text-gray-700 hover:bg-gray-50 transition-colors"
        >
          {showPct ? 'Show counts' : 'Show %'}
        </button>
      </div>
      <ResponsiveContainer width="100%" height={400}>
        <BarChart
          data={showPct ? pctData : data}
          layout="vertical"
          margin={{ top: 5, right: 30, left: 100, bottom: 5 }}
        >
          <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
          <XAxis
            type="number"
            tick={{ fontSize: 11 }}
            stroke="#6b7280"
            domain={showPct ? [0, 100] : [0, 'auto']}
            allowDataOverflow={showPct}
            tickFormatter={showPct ? (v) => `${v}%` : undefined}
          />
          <YAxis
            dataKey="region"
            type="category"
            width={90}
            tick={{ fontSize: 10 }}
            stroke="#6b7280"
          />
          <Tooltip
            formatter={(value: number) => (showPct ? `${value}%` : value)}
          />
          <Legend
            content={() => (
              <div className="flex flex-wrap justify-center gap-x-4 gap-y-1 mt-2 text-xs text-gray-700">
                {BOUNTY_TIER_LABELS.map(({ label, color }) => (
                  <span key={label} className="flex items-center gap-1">
                    <span
                      className="inline-block w-3 h-3 rounded-sm"
                      style={{ backgroundColor: color }}
                    />
                    {label}
                  </span>
                ))}
              </div>
            )}
          />
          {BOUNTY_TIER_LABELS.map(({ label, color }) => (
            <Bar
              key={label}
              dataKey={label}
              stackId="a"
              fill={color}
              name={label}
              isAnimationActive={false}
            />
          ))}
        </BarChart>
      </ResponsiveContainer>
      <EmbedFooter />
    </div>
  )
}

// ── #5 Most Loyal ───────────────────────────────────────────────────────────

function EmbedMostLoyal({
  data,
}: {
  data: ReturnType<typeof computeMostLoyal>
}) {
  return (
    <div className="p-4 font-sans">
      <h2 className="text-lg font-semibold text-gray-900 mb-3">
        Most &quot;Loyal&quot; Characters
      </h2>
      <ResponsiveContainer width="100%" height={400}>
        <BarChart
          data={data}
          layout="vertical"
          margin={{ top: 5, right: 30, left: 120, bottom: 5 }}
        >
          <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
          <XAxis
            type="number"
            tick={{ fontSize: 11 }}
            stroke="#6b7280"
            label={{
              value: 'Density (%)',
              position: 'insideBottom',
              offset: -5,
              style: { fontSize: 11, fill: '#6b7280' },
            }}
          />
          <YAxis
            dataKey="name"
            type="category"
            width={110}
            tick={{ fontSize: 10 }}
            stroke="#6b7280"
          />
          <Tooltip
            formatter={(value: number) => [`${value}%`, 'Density']}
            labelFormatter={(label: string) => {
              const c = data.find((l) => l.name === label)
              return c
                ? `${label} — ${c.appearances} appearances over ${c.span} chapters`
                : label
            }}
          />
          <Bar dataKey="density" fill="#6366f1" radius={[0, 8, 8, 0]} />
        </BarChart>
      </ResponsiveContainer>
      <EmbedFooter />
    </div>
  )
}

// ── #6 Arc Count Distribution ───────────────────────────────────────────────

function EmbedArcCountDistribution({
  data,
}: {
  data: ReturnType<typeof computeArcCountDistribution>
}) {
  return (
    <div className="p-4 font-sans">
      <h2 className="text-lg font-semibold text-gray-900 mb-3">
        One-Arc Wonders vs Recurring Cast
      </h2>
      <ResponsiveContainer width="100%" height={350}>
        <BarChart
          data={data}
          margin={{ top: 20, right: 30, left: 20, bottom: 5 }}
        >
          <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
          <XAxis dataKey="arcCount" tick={{ fontSize: 11 }} stroke="#6b7280" />
          <YAxis tick={{ fontSize: 11 }} stroke="#6b7280" />
          <Tooltip />
          <Bar
            dataKey="characterCount"
            fill="#8b5cf6"
            radius={[8, 8, 0, 0]}
            name="Characters"
            // eslint-disable-next-line @typescript-eslint/no-explicit-any
            label={(props: any) => {
              const { x, y, width, value } = props
              const total = data.reduce((s, d) => s + d.characterCount, 0)
              const pct = total > 0 ? Math.round((value / total) * 100) : 0
              return (
                <text
                  x={x + width / 2}
                  y={y - 5}
                  textAnchor="middle"
                  fontSize={11}
                  fill="#374151"
                >
                  {value} ({pct}%)
                </text>
              )
            }}
          />
        </BarChart>
      </ResponsiveContainer>
      <EmbedFooter />
    </div>
  )
}

// ── #6b Saga Count Distribution ─────────────────────────────────────────────

function EmbedSagaCountDistribution({
  data,
}: {
  data: ReturnType<typeof computeSagaCountDistribution>
}) {
  return (
    <div className="p-4 font-sans">
      <h2 className="text-lg font-semibold text-gray-900 mb-3">
        One-Saga Wonders vs Recurring Cast
      </h2>
      <ResponsiveContainer width="100%" height={350}>
        <BarChart
          data={data}
          margin={{ top: 20, right: 30, left: 20, bottom: 5 }}
        >
          <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
          <XAxis dataKey="sagaCount" tick={{ fontSize: 11 }} stroke="#6b7280" />
          <YAxis tick={{ fontSize: 11 }} stroke="#6b7280" />
          <Tooltip />
          <Bar
            dataKey="characterCount"
            fill="#ec4899"
            radius={[8, 8, 0, 0]}
            name="Characters"
            // eslint-disable-next-line @typescript-eslint/no-explicit-any
            label={(props: any) => {
              const { x, y, width, value } = props
              const total = data.reduce((s, d) => s + d.characterCount, 0)
              const pct = total > 0 ? Math.round((value / total) * 100) : 0
              return (
                <text
                  x={x + width / 2}
                  y={y - 5}
                  textAnchor="middle"
                  fontSize={11}
                  fill="#374151"
                >
                  {value} ({pct}%)
                </text>
              )
            }}
          />
        </BarChart>
      </ResponsiveContainer>
      <EmbedFooter />
    </div>
  )
}

// ── #7 Arc Intro Rate ───────────────────────────────────────────────────────

function EmbedArcIntroRate({
  data,
}: {
  data: ReturnType<typeof computeArcIntroRate>
}) {
  const [mode, setMode] = useState<'both' | 'new' | 'returning'>('both')

  return (
    <div className="p-4 font-sans">
      <div className="flex items-center justify-between mb-3">
        <h2 className="text-lg font-semibold text-gray-900">
          Characters per Arc (New vs Returning)
        </h2>
        <div className="flex items-center gap-2">
          {(['both', 'new', 'returning'] as const).map((m) => (
            <button
              key={m}
              onClick={() => setMode(m)}
              className={`px-2 py-1 text-xs rounded-md transition-colors ${
                mode === m
                  ? 'bg-blue-600 text-white'
                  : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
              }`}
            >
              {m === 'both' ? 'Both' : m === 'new' ? 'New' : 'Returning'}
            </button>
          ))}
        </div>
      </div>
      <ResponsiveContainer width="100%" height={400}>
        <BarChart
          data={data}
          margin={{ top: 5, right: 30, left: 20, bottom: 80 }}
        >
          <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
          <XAxis
            dataKey="arc"
            tick={{ fontSize: 9 }}
            angle={-45}
            textAnchor="end"
            height={100}
            stroke="#6b7280"
          />
          <YAxis tick={{ fontSize: 11 }} stroke="#6b7280" />
          <Tooltip
            labelFormatter={(label: string) => {
              const d = data.find((a) => a.arc === label)
              return `${label} (${d?.saga || 'Unknown'})`
            }}
          />
          <Legend />
          {(mode === 'both' || mode === 'returning') && (
            <Bar
              dataKey="returningCharacters"
              name="Returning Characters"
              stackId="characters"
              fill="#f59e0b"
              radius={mode === 'returning' ? [4, 4, 0, 0] : undefined}
            />
          )}
          {(mode === 'both' || mode === 'new') && (
            <Bar
              dataKey="newCharacters"
              name="New Characters"
              stackId="characters"
              fill="#3b82f6"
              radius={[4, 4, 0, 0]}
            />
          )}
        </BarChart>
      </ResponsiveContainer>
      <EmbedFooter />
    </div>
  )
}

// ── #7b Saga Intro Rate ─────────────────────────────────────────────────────

function EmbedSagaIntroRate({
  data,
}: {
  data: ReturnType<typeof computeSagaIntroRate>
}) {
  const [mode, setMode] = useState<'both' | 'new' | 'returning'>('both')

  return (
    <div className="p-4 font-sans">
      <div className="flex items-center justify-between mb-3">
        <h2 className="text-lg font-semibold text-gray-900">
          Characters per Saga (New vs Returning)
        </h2>
        <div className="flex items-center gap-2">
          {(['both', 'new', 'returning'] as const).map((m) => (
            <button
              key={m}
              onClick={() => setMode(m)}
              className={`px-2 py-1 text-xs rounded-md transition-colors ${
                mode === m
                  ? 'bg-blue-600 text-white'
                  : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
              }`}
            >
              {m === 'both' ? 'Both' : m === 'new' ? 'New' : 'Returning'}
            </button>
          ))}
        </div>
      </div>
      <ResponsiveContainer width="100%" height={400}>
        <BarChart
          data={data}
          margin={{ top: 5, right: 30, left: 20, bottom: 80 }}
        >
          <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
          <XAxis
            dataKey="saga"
            tick={{ fontSize: 10 }}
            angle={-45}
            textAnchor="end"
            height={100}
            stroke="#6b7280"
          />
          <YAxis tick={{ fontSize: 11 }} stroke="#6b7280" />
          <Tooltip />
          <Legend />
          {(mode === 'both' || mode === 'returning') && (
            <Bar
              dataKey="returningCharacters"
              name="Returning Characters"
              stackId="characters"
              fill="#f59e0b"
              radius={mode === 'returning' ? [4, 4, 0, 0] : undefined}
            />
          )}
          {(mode === 'both' || mode === 'new') && (
            <Bar
              dataKey="newCharacters"
              name="New Characters"
              stackId="characters"
              fill="#3b82f6"
              radius={[4, 4, 0, 0]}
            />
          )}
        </BarChart>
      </ResponsiveContainer>
      <EmbedFooter />
    </div>
  )
}

// ── #8 Gap Analysis ─────────────────────────────────────────────────────────

function EmbedGapAnalysis({
  data,
}: {
  data: ReturnType<typeof computeLongestGaps>
}) {
  return (
    <div className="p-4 font-sans">
      <h2 className="text-lg font-semibold text-gray-900 mb-3">
        Longest Disappearances
      </h2>
      <div className="overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b-2 border-gray-200">
              <th className="text-left py-3 px-3 font-semibold text-gray-900">
                Character
              </th>
              <th className="text-right py-3 px-3 font-semibold text-gray-900">
                Gap (chapters)
              </th>
              <th className="text-right py-3 px-3 font-semibold text-gray-900">
                From Ch.
              </th>
              <th className="text-right py-3 px-3 font-semibold text-gray-900">
                To Ch.
              </th>
              <th className="text-right py-3 px-3 font-semibold text-gray-900">
                Total Appearances
              </th>
            </tr>
          </thead>
          <tbody>
            {data.map((g, i) => (
              <tr
                key={g.name}
                className={`border-b border-gray-100 ${i % 2 === 0 ? 'bg-gray-50/50' : ''}`}
              >
                <td className="py-2 px-3 font-medium text-gray-900">
                  {g.name}
                </td>
                <td className="py-2 px-3 text-right font-bold text-red-600">
                  {g.gapLength}
                </td>
                <td className="py-2 px-3 text-right text-gray-600">
                  {g.gapStart}
                </td>
                <td className="py-2 px-3 text-right text-gray-600">
                  {g.gapEnd}
                </td>
                <td className="py-2 px-3 text-right text-gray-600">
                  {g.totalAppearances}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <EmbedFooter />
    </div>
  )
}

// ── #9 Arc Length Trend ──────────────────────────────────────────────────────

function EmbedArcLengthTrend({
  data,
}: {
  data: ReturnType<typeof computeArcLengths>
}) {
  return (
    <div className="p-4 font-sans">
      <h2 className="text-lg font-semibold text-gray-900 mb-3">
        Arc Length Trend
      </h2>
      <ResponsiveContainer width="100%" height={400}>
        <BarChart
          data={data}
          margin={{ top: 5, right: 30, left: 20, bottom: 80 }}
        >
          <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
          <XAxis
            dataKey="arc"
            tick={{ fontSize: 9 }}
            angle={-45}
            textAnchor="end"
            height={100}
            stroke="#6b7280"
          />
          <YAxis tick={{ fontSize: 11 }} stroke="#6b7280" />
          <Tooltip
            labelFormatter={(label: string) => {
              const d = data.find((a) => a.arc === label)
              return `${label} (${d?.saga || ''})`
            }}
          />
          <Bar dataKey="chapters" name="Chapters" radius={[4, 4, 0, 0]}>
            {data.map((entry, i) => {
              const sagaNames = [...new Set(data.map((a) => a.saga))]
              const colorIdx = sagaNames.indexOf(entry.saga)
              return (
                <Cell
                  key={i}
                  fill={SAGA_COLORS[colorIdx % SAGA_COLORS.length]}
                />
              )
            })}
          </Bar>
        </BarChart>
      </ResponsiveContainer>
      <EmbedFooter />
    </div>
  )
}

// ── #10 Pages per Arc ───────────────────────────────────────────────────────

function EmbedPagesPerArc({
  data,
}: {
  data: ReturnType<typeof computePagesPerArc>
}) {
  return (
    <div className="p-4 font-sans">
      <h2 className="text-lg font-semibold text-gray-900 mb-3">
        Total Pages per Arc
      </h2>
      <ResponsiveContainer width="100%" height={400}>
        <BarChart
          data={data}
          margin={{ top: 5, right: 30, left: 20, bottom: 80 }}
        >
          <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
          <XAxis
            dataKey="arc"
            tick={{ fontSize: 9 }}
            angle={-45}
            textAnchor="end"
            height={100}
            stroke="#6b7280"
          />
          <YAxis tick={{ fontSize: 11 }} stroke="#6b7280" />
          <Tooltip
            formatter={(value: number, name: string) =>
              name === 'totalPages'
                ? [`${value.toLocaleString()} pages`, 'Total Pages']
                : [value, name]
            }
          />
          <Bar
            dataKey="totalPages"
            name="Total Pages"
            fill="#f59e0b"
            radius={[4, 4, 0, 0]}
          />
        </BarChart>
      </ResponsiveContainer>
      <EmbedFooter />
    </div>
  )
}

// ── #11 Saga Pacing ─────────────────────────────────────────────────────────

function EmbedSagaPacing({
  data,
}: {
  data: ReturnType<typeof computeSagaPacing>
}) {
  return (
    <div className="p-4 font-sans">
      <h2 className="text-lg font-semibold text-gray-900 mb-3">
        Saga Pacing Comparison
      </h2>
      <div className="overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b-2 border-gray-200">
              <th className="text-left py-3 px-3 font-semibold text-gray-900">
                Saga
              </th>
              <th className="text-right py-3 px-3 font-semibold text-gray-900">
                Arcs
              </th>
              <th className="text-right py-3 px-3 font-semibold text-gray-900">
                Chapters
              </th>
              <th className="text-right py-3 px-3 font-semibold text-gray-900">
                Pages
              </th>
              <th className="text-right py-3 px-3 font-semibold text-gray-900">
                Active Characters
              </th>
              <th className="text-right py-3 px-3 font-semibold text-gray-900">
                New Characters
              </th>
              <th className="text-right py-3 px-3 font-semibold text-gray-900">
                Chars/Ch.
              </th>
            </tr>
          </thead>
          <tbody>
            {data.map((s, i) => (
              <tr
                key={s.saga}
                className={`border-b border-gray-100 ${i % 2 === 0 ? 'bg-gray-50/50' : ''}`}
              >
                <td className="py-2 px-3 font-medium text-gray-900">
                  {s.saga}
                </td>
                <td className="py-2 px-3 text-right text-gray-600">
                  {s.arcCount}
                </td>
                <td className="py-2 px-3 text-right text-gray-600">
                  {s.totalChapters}
                </td>
                <td className="py-2 px-3 text-right text-gray-600">
                  {s.totalPages.toLocaleString()}
                </td>
                <td className="py-2 px-3 text-right font-medium text-blue-600">
                  {s.characterCount}
                </td>
                <td className="py-2 px-3 text-right font-medium text-emerald-600">
                  {s.newCharacters}
                </td>
                <td className="py-2 px-3 text-right font-medium text-purple-600">
                  {s.density}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <EmbedFooter />
    </div>
  )
}

// ── #12 Yearly Releases ─────────────────────────────────────────────────────

function EmbedYearlyReleases({
  data,
}: {
  data: ReturnType<typeof computeYearlyReleases>
}) {
  return (
    <div className="p-4 font-sans">
      <h2 className="text-lg font-semibold text-gray-900 mb-3">
        Chapters per Year
      </h2>
      <ResponsiveContainer width="100%" height={350}>
        <BarChart
          data={data}
          margin={{ top: 5, right: 30, left: 20, bottom: 5 }}
        >
          <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
          <XAxis dataKey="year" tick={{ fontSize: 11 }} stroke="#6b7280" />
          <YAxis tick={{ fontSize: 11 }} stroke="#6b7280" />
          <Tooltip />
          <Legend />
          <Bar
            dataKey="chapters"
            fill="#3b82f6"
            name="Chapters Released"
            radius={[4, 4, 0, 0]}
          />
          <Bar
            dataKey="breaks"
            fill="#fbbf24"
            name="Estimated Breaks"
            radius={[4, 4, 0, 0]}
          />
        </BarChart>
      </ResponsiveContainer>
      <EmbedFooter />
    </div>
  )
}

// ── #13 Blood Type Comparison ───────────────────────────────────────────────

function EmbedBloodTypeComparison({
  data,
}: {
  data: ReturnType<typeof computeBloodTypeComparison>
}) {
  return (
    <div className="p-4 font-sans">
      <h2 className="text-lg font-semibold text-gray-900 mb-3">
        Blood Type: One Piece vs Japan
      </h2>
      <ResponsiveContainer width="100%" height={300}>
        <BarChart
          data={data}
          margin={{ top: 5, right: 30, left: 20, bottom: 5 }}
        >
          <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
          <XAxis dataKey="bloodType" tick={{ fontSize: 12 }} stroke="#6b7280" />
          <YAxis
            tick={{ fontSize: 11 }}
            stroke="#6b7280"
            label={{
              value: '%',
              position: 'insideTopLeft',
              style: { fontSize: 11, fill: '#6b7280' },
            }}
          />
          <Tooltip formatter={(value: number) => [`${value}%`]} />
          <Legend />
          <Bar
            dataKey="opPercent"
            fill="#3b82f6"
            name="One Piece"
            radius={[4, 4, 0, 0]}
          />
          <Bar
            dataKey="japanPercent"
            fill="#f59e0b"
            name="Japan (Real)"
            radius={[4, 4, 0, 0]}
          />
        </BarChart>
      </ResponsiveContainer>
      <EmbedFooter />
    </div>
  )
}

// ── #14 Birthday Distribution ───────────────────────────────────────────────

function EmbedBirthdayDistribution({
  data,
}: {
  data: ReturnType<typeof computeBirthdayDistribution>
}) {
  return (
    <div className="p-4 font-sans">
      <h2 className="text-lg font-semibold text-gray-900 mb-3">
        Birthday Calendar by Month
      </h2>
      <ResponsiveContainer width="100%" height={300}>
        <BarChart
          data={data}
          margin={{ top: 5, right: 30, left: 20, bottom: 5 }}
        >
          <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
          <XAxis dataKey="month" tick={{ fontSize: 12 }} stroke="#6b7280" />
          <YAxis tick={{ fontSize: 11 }} stroke="#6b7280" />
          <Tooltip />
          <Bar
            dataKey="count"
            fill="#ec4899"
            name="Birthdays"
            radius={[4, 4, 0, 0]}
          />
        </BarChart>
      </ResponsiveContainer>
      <EmbedFooter />
    </div>
  )
}

// ── #15 Origin Regions ──────────────────────────────────────────────────────

function EmbedOriginRegions({
  data,
}: {
  data: ReturnType<typeof computeRegionCounts>
}) {
  return (
    <div className="p-4 font-sans">
      <h2 className="text-lg font-semibold text-gray-900 mb-3">
        Origin Region Bubble Chart
      </h2>
      <ResponsiveContainer width="100%" height={350}>
        <PieChart>
          <Pie
            data={data.slice(0, 15).map((r) => ({
              ...r,
              [r.region]: r.count,
            }))}
            dataKey="count"
            nameKey="region"
            cx="50%"
            cy="50%"
            outerRadius={120}
            label={(props: {
              region?: string
              count?: number
              name?: string
              value?: number
            }) =>
              `${props.region || props.name || ''} (${props.count ?? props.value ?? 0})`
            }
            labelLine={{ stroke: '#6b7280', strokeWidth: 1 }}
          >
            {data.slice(0, 15).map((_, i) => (
              <Cell key={i} fill={SAGA_COLORS[i % SAGA_COLORS.length]} />
            ))}
          </Pie>
          <Tooltip />
        </PieChart>
      </ResponsiveContainer>
      <EmbedFooter />
    </div>
  )
}

// ── #16 Age Distribution ────────────────────────────────────────────────────

function EmbedAgeDistribution({
  data,
}: {
  data: ReturnType<typeof computeAgeDistribution>
}) {
  return (
    <div className="p-4 font-sans">
      <h2 className="text-lg font-semibold text-gray-900 mb-3">
        Age Distribution by Status
      </h2>
      <ResponsiveContainer width="100%" height={350}>
        <BarChart
          data={data}
          margin={{ top: 5, right: 30, left: 20, bottom: 5 }}
        >
          <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
          <XAxis dataKey="ageRange" tick={{ fontSize: 11 }} stroke="#6b7280" />
          <YAxis tick={{ fontSize: 11 }} stroke="#6b7280" />
          <Tooltip />
          <Legend />
          <Bar dataKey="alive" stackId="a" fill="#10b981" name="Alive" />
          <Bar dataKey="deceased" stackId="a" fill="#ef4444" name="Deceased" />
          <Bar dataKey="unknown" stackId="a" fill="#9ca3af" name="Unknown" />
        </BarChart>
      </ResponsiveContainer>
      <EmbedFooter />
    </div>
  )
}

// ── #17 Cover Stars ─────────────────────────────────────────────────────────

function EmbedCoverStars({
  data,
}: {
  data: ReturnType<typeof computeCoverStars>
}) {
  return (
    <div className="p-4 font-sans">
      <h2 className="text-lg font-semibold text-gray-900 mb-3">
        Cover Page Stars
      </h2>
      <ResponsiveContainer width="100%" height={500}>
        <BarChart
          data={data}
          layout="vertical"
          margin={{ top: 5, right: 30, left: 120, bottom: 5 }}
        >
          <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
          <XAxis type="number" tick={{ fontSize: 11 }} stroke="#6b7280" />
          <YAxis
            dataKey="name"
            type="category"
            width={110}
            tick={{ fontSize: 10 }}
            stroke="#6b7280"
          />
          <Tooltip />
          <Bar
            dataKey="coverAppearances"
            fill="#f59e0b"
            name="Cover Appearances"
            radius={[0, 8, 8, 0]}
          />
        </BarChart>
      </ResponsiveContainer>
      <EmbedFooter />
    </div>
  )
}

// ── #18 Cover vs Main ───────────────────────────────────────────────────────

function EmbedCoverVsMain({
  data,
}: {
  data: ReturnType<typeof computeCoverVsMain>
}) {
  return (
    <div className="p-4 font-sans">
      <h2 className="text-lg font-semibold text-gray-900 mb-3">
        Cover vs Main Story Appearances
      </h2>
      <ResponsiveContainer width="100%" height={400}>
        <ScatterChart margin={{ top: 10, right: 30, left: 20, bottom: 10 }}>
          <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
          <XAxis
            type="number"
            dataKey="main"
            name="Main Story"
            tick={{ fontSize: 11 }}
            stroke="#6b7280"
          />
          <YAxis
            type="number"
            dataKey="cover"
            name="Cover"
            tick={{ fontSize: 11 }}
            stroke="#6b7280"
          />
          <Tooltip
            labelFormatter={(
              _: unknown,
              payload: ReadonlyArray<{ payload?: { name?: string } }>
            ) => payload?.[0]?.payload?.name || ''}
          />
          <Scatter data={data} fill="#8b5cf6" fillOpacity={0.5} />
        </ScatterChart>
      </ResponsiveContainer>
      <EmbedFooter />
    </div>
  )
}

// ── #19 Arc Density ─────────────────────────────────────────────────────────

function EmbedArcDensity({
  data,
}: {
  data: ReturnType<typeof computeArcDensity>
}) {
  return (
    <div className="p-4 font-sans">
      <h2 className="text-lg font-semibold text-gray-900 mb-3">
        Character Cast Size per Arc
      </h2>
      <ResponsiveContainer width="100%" height={400}>
        <BarChart
          data={data}
          margin={{ top: 5, right: 30, left: 20, bottom: 80 }}
        >
          <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
          <XAxis
            dataKey="arc"
            tick={{ fontSize: 9 }}
            angle={-45}
            textAnchor="end"
            height={100}
            stroke="#6b7280"
          />
          <YAxis tick={{ fontSize: 11 }} stroke="#6b7280" />
          <Tooltip
            formatter={(value: number, name: string) =>
              name === 'uniqueCharacters'
                ? [value, 'Unique Characters']
                : [value, name]
            }
          />
          <Bar
            dataKey="uniqueCharacters"
            fill="#06b6d4"
            name="Unique Characters"
            radius={[4, 4, 0, 0]}
          />
        </BarChart>
      </ResponsiveContainer>
      <EmbedFooter />
    </div>
  )
}

// ── #20 Data Completeness ───────────────────────────────────────────────────

interface CompletenessField {
  field: string
  filled: number
  total: number
  percent: number
}

function EmbedDataCompleteness({ data }: { data: CompletenessField[] }) {
  return (
    <div className="p-4 font-sans">
      <h2 className="text-lg font-semibold text-gray-900 mb-3">
        The Completeness Gap
      </h2>
      <ResponsiveContainer width="100%" height={300}>
        <BarChart
          data={data}
          margin={{ top: 5, right: 30, left: 20, bottom: 5 }}
        >
          <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
          <XAxis dataKey="field" tick={{ fontSize: 11 }} stroke="#6b7280" />
          <YAxis
            tick={{ fontSize: 11 }}
            stroke="#6b7280"
            domain={[0, 100]}
            label={{
              value: '%',
              position: 'insideTopLeft',
              style: { fontSize: 11, fill: '#6b7280' },
            }}
          />
          <Tooltip
            formatter={(
              value: number,
              _name: string,
              props: { payload?: CompletenessField }
            ) => [
              `${value}% (${props.payload?.filled || 0}/${props.payload?.total || 0})`,
              'Completeness',
            ]}
          />
          <Bar dataKey="percent" name="Completeness" radius={[4, 4, 0, 0]}>
            {data.map((entry, i) => (
              <Cell
                key={i}
                fill={
                  entry.percent >= 80
                    ? '#10b981'
                    : entry.percent >= 50
                      ? '#f59e0b'
                      : '#ef4444'
                }
              />
            ))}
          </Bar>
        </BarChart>
      </ResponsiveContainer>
      <EmbedFooter />
    </div>
  )
}

// ── #21 Top Characters per Saga ─────────────────────────────────────────────

function EmbedTopCharactersPerSaga({
  data,
}: {
  data: ReturnType<typeof computeTopCharactersPerSaga>
}) {
  const [shpFilter, setSHPFilter] = useState<'all' | 'hide' | 'only'>('hide')
  const [showPct, setShowPct] = useState(false)

  return (
    <div className="p-4 font-sans">
      <div className="flex items-center justify-between mb-3">
        <h2 className="text-lg font-semibold text-gray-900">
          Top Characters per Saga
        </h2>
        <div className="flex items-center gap-2">
          <div className="inline-flex rounded-lg border border-gray-200 overflow-hidden text-xs">
            {(['all', 'hide', 'only'] as const).map((v) => (
              <button
                key={v}
                onClick={() => setSHPFilter(v)}
                className={`px-2 py-1 transition-colors ${shpFilter === v ? 'bg-blue-600 text-white font-medium' : 'bg-white text-gray-600 hover:bg-gray-50'}`}
              >
                {v === 'all' ? 'All' : v === 'hide' ? 'Hide SHP' : 'Only SHP'}
              </button>
            ))}
          </div>
          <div className="inline-flex rounded-lg border border-gray-200 overflow-hidden text-xs">
            <button
              onClick={() => setShowPct(false)}
              className={`px-2 py-1 transition-colors ${!showPct ? 'bg-blue-600 text-white font-medium' : 'bg-white text-gray-600 hover:bg-gray-50'}`}
            >
              Count
            </button>
            <button
              onClick={() => setShowPct(true)}
              className={`px-2 py-1 transition-colors ${showPct ? 'bg-blue-600 text-white font-medium' : 'bg-white text-gray-600 hover:bg-gray-50'}`}
            >
              %
            </button>
          </div>
        </div>
      </div>
      <RankingTable
        items={data.map((s) => ({
          id: s.sagaId,
          title: s.sagaTitle,
          totalChapters: s.totalChapters,
          characters: s.characters,
        }))}
        linkPrefix="/sagas/"
        shpFilter={shpFilter}
        showPct={showPct}
      />
      <EmbedFooter />
    </div>
  )
}

// ── #22 Top Characters per Arc ──────────────────────────────────────────────

function EmbedTopCharactersPerArc({
  data,
}: {
  data: ReturnType<typeof computeTopCharactersPerArc>
}) {
  const [shpFilter, setSHPFilter] = useState<'all' | 'hide' | 'only'>('hide')
  const [showPct, setShowPct] = useState(false)

  return (
    <div className="p-4 font-sans">
      <div className="flex items-center justify-between mb-3">
        <h2 className="text-lg font-semibold text-gray-900">
          Top Characters per Arc
        </h2>
        <div className="flex items-center gap-2">
          <div className="inline-flex rounded-lg border border-gray-200 overflow-hidden text-xs">
            {(['all', 'hide', 'only'] as const).map((v) => (
              <button
                key={v}
                onClick={() => setSHPFilter(v)}
                className={`px-2 py-1 transition-colors ${shpFilter === v ? 'bg-blue-600 text-white font-medium' : 'bg-white text-gray-600 hover:bg-gray-50'}`}
              >
                {v === 'all' ? 'All' : v === 'hide' ? 'Hide SHP' : 'Only SHP'}
              </button>
            ))}
          </div>
          <div className="inline-flex rounded-lg border border-gray-200 overflow-hidden text-xs">
            <button
              onClick={() => setShowPct(false)}
              className={`px-2 py-1 transition-colors ${!showPct ? 'bg-blue-600 text-white font-medium' : 'bg-white text-gray-600 hover:bg-gray-50'}`}
            >
              Count
            </button>
            <button
              onClick={() => setShowPct(true)}
              className={`px-2 py-1 transition-colors ${showPct ? 'bg-blue-600 text-white font-medium' : 'bg-white text-gray-600 hover:bg-gray-50'}`}
            >
              %
            </button>
          </div>
        </div>
      </div>
      <RankingTable
        items={data.map((a) => ({
          id: a.arcId,
          title: a.arcTitle,
          totalChapters: a.totalChapters,
          characters: a.characters,
        }))}
        linkPrefix="/arcs/"
        shpFilter={shpFilter}
        showPct={showPct}
      />
      <EmbedFooter />
    </div>
  )
}

// ── #23 Largest Groups ──────────────────────────────────────────────────────

function EmbedLargestGroups({
  data,
}: {
  data: ReturnType<typeof computeLargestGroups>
}) {
  return (
    <div className="p-4 font-sans">
      <h2 className="text-lg font-semibold text-gray-900 mb-3">
        Largest Crews &amp; Organizations
      </h2>
      <ResponsiveContainer width="100%" height={600}>
        <BarChart
          data={data}
          layout="vertical"
          margin={{ top: 5, right: 30, left: 160, bottom: 5 }}
        >
          <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
          <XAxis type="number" tick={{ fontSize: 11 }} stroke="#6b7280" />
          <YAxis
            dataKey="groupName"
            type="category"
            width={150}
            tick={{ fontSize: 9 }}
            stroke="#6b7280"
          />
          <Tooltip />
          <Legend />
          <Bar
            dataKey="currentMembers"
            name="Current"
            stackId="members"
            fill="#10b981"
          />
          <Bar
            dataKey="formerMembers"
            name="Former / Defected"
            stackId="members"
            fill="#f59e0b"
          />
        </BarChart>
      </ResponsiveContainer>
      <EmbedFooter />
    </div>
  )
}

// ── #24 Crew Loyalty ────────────────────────────────────────────────────────

function EmbedCrewLoyalty({
  data,
}: {
  data: ReturnType<typeof computeCrewLoyalty>
}) {
  return (
    <div className="p-4 font-sans">
      <h2 className="text-lg font-semibold text-gray-900 mb-3">
        Crew Loyalty vs Turnover
      </h2>
      <ResponsiveContainer width="100%" height={500}>
        <BarChart
          data={data}
          layout="vertical"
          margin={{ top: 5, right: 30, left: 160, bottom: 5 }}
        >
          <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
          <XAxis type="number" tick={{ fontSize: 11 }} stroke="#6b7280" />
          <YAxis
            dataKey="groupName"
            type="category"
            width={150}
            tick={{ fontSize: 9 }}
            stroke="#6b7280"
          />
          <Tooltip />
          <Legend />
          <Bar
            dataKey="current"
            name="Current"
            stackId="status"
            fill="#10b981"
          />
          <Bar dataKey="former" name="Former" stackId="status" fill="#fbbf24" />
          <Bar
            dataKey="defected"
            name="Defected"
            stackId="status"
            fill="#ef4444"
          />
          <Bar dataKey="other" name="Other" stackId="status" fill="#9ca3af" />
        </BarChart>
      </ResponsiveContainer>
      <EmbedFooter />
    </div>
  )
}

// ── Shared Components ───────────────────────────────────────────────────────

interface RankingItem {
  id: string
  title: string
  totalChapters: number
  characters: { id: string; name: string; count: number }[]
}

function RankingTable({
  items,
  linkPrefix,
  shpFilter,
  showPct,
}: {
  items: RankingItem[]
  linkPrefix: string
  shpFilter: 'all' | 'hide' | 'only'
  showPct: boolean
}) {
  const displayRows = 20
  const filtered = items.map((item) => ({
    ...item,
    characters: (shpFilter === 'hide'
      ? item.characters.filter((c) => !STRAW_HAT_IDS.has(c.id))
      : shpFilter === 'only'
        ? item.characters.filter((c) => STRAW_HAT_IDS.has(c.id))
        : item.characters
    ).slice(0, displayRows),
  }))

  return (
    <div className="overflow-x-auto border border-gray-200 rounded-lg">
      <table className="w-full text-sm">
        <thead>
          <tr className="border-b border-gray-200">
            <th className="sticky left-0 z-20 bg-gray-50 px-3 py-2 text-left font-semibold text-gray-700 min-w-[40px] border-r border-gray-200">
              #
            </th>
            {filtered.map((item) => (
              <th
                key={item.id}
                className="bg-gray-50 px-2 py-2 text-center font-medium text-gray-600 min-w-[140px]"
              >
                <Link
                  to={`${linkPrefix}${item.id}`}
                  target="_blank"
                  className="hover:text-blue-600 transition-colors text-xs"
                >
                  <div>{item.title}</div>
                  <div className="text-[10px] text-gray-400 font-normal">
                    {item.totalChapters} chapters
                  </div>
                </Link>
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {Array.from({ length: displayRows }, (_, rowIdx) => (
            <tr
              key={rowIdx}
              className={`border-b border-gray-100 ${rowIdx % 2 === 0 ? '' : 'bg-gray-50/30'}`}
            >
              <td className="sticky left-0 z-10 bg-white px-3 py-1.5 text-center font-medium text-gray-400 border-r border-gray-200 tabular-nums">
                {rowIdx + 1}
              </td>
              {filtered.map((item) => {
                const char = item.characters[rowIdx]
                if (!char) {
                  return (
                    <td
                      key={item.id}
                      className="px-2 py-1.5 text-center text-gray-300"
                    >
                      &ndash;
                    </td>
                  )
                }
                const isSHP = STRAW_HAT_IDS.has(char.id)
                const pct =
                  Math.round((char.count / item.totalChapters) * 1000) / 10
                const isOver50 = pct > 50
                return (
                  <td
                    key={item.id}
                    className={`px-2 py-1.5 text-xs ${isSHP ? 'bg-amber-50' : ''}`}
                  >
                    <Link
                      to={`/characters/${char.id}`}
                      target="_blank"
                      className={`hover:text-blue-600 transition-colors ${isSHP ? 'font-medium text-amber-700' : ''} ${isOver50 ? 'font-bold' : ''}`}
                    >
                      {char.name}
                    </Link>
                    <span
                      className={`ml-1 tabular-nums ${isOver50 ? 'font-bold text-gray-600' : 'text-gray-400'}`}
                    >
                      ({showPct ? `${pct}%` : char.count})
                    </span>
                  </td>
                )
              })}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}

function EmbedFooter() {
  const baseUrl = window.location.origin + window.location.pathname
  return (
    <div className="mt-3 flex items-center justify-between text-[10px] text-gray-400">
      <span>One Piece of Data</span>
      <a
        href={`${baseUrl}#/analytics/insights`}
        target="_blank"
        rel="noopener noreferrer"
        className="hover:text-blue-500 transition-colors"
      >
        View full insights &rarr;
      </a>
    </div>
  )
}

export default EmbedInsightPage
