/**
 * Embed renderers for all insight charts.
 *
 * Each chart is accessible at: /#/embed/insights/<slug>
 * Permalink on the main page:  /#/analytics/<topic>#<slug>
 *
 * ┌────────────────────────────────────────────────┬────────────────────────────┬────────────────────────────┐
 * │ Title                                          │ Slug                       │ Interactive Filters        │
 * ├────────────────────────────────────────────────┼────────────────────────────┼────────────────────────────┤
 * │ Age Distribution by Status                     │ age-distribution           │ —                          │
 * │ Blood Type Distribution                        │ blood-type-comparison      │ —                          │
 * │ Bounty Distribution by Power Tier              │ bounty-distribution        │ —                          │
 * │ Bounty Jumps                                   │ bounty-jumps               │ Sortable table             │
 * │ Bounty Tier Distribution by Region             │ region-bounty-tier         │ Count / %                  │
 * │ Bounty vs Appearance Count                     │ bounty-vs-appearance       │ SHP toggle                 │
 * │ Cast Complexity Over Time                      │ cast-complexity            │ —                          │
 * │ Characters per Arc (New vs Returning)          │ arc-intro-rate             │ Both / New / Returning     │
 * │ Characters per Saga (New vs Returning)         │ saga-intro-rate            │ Both / New / Returning     │
 * │ Crew Loyalty vs Turnover                       │ crew-loyalty               │ —                          │
 * │ Largest Crews & Organizations                  │ largest-groups             │ —                          │
 * │ Longest Disappearances                         │ gap-analysis               │ Sortable table             │
 * │ Most Consistent Presence                       │ most-loyal                 │ —                          │
 * │ One-Arc / One-Saga Wonders vs Recurring Cast   │ wonders-distribution       │ Arcs / Sagas               │
 * │ Origin Region Distribution                     │ origin-regions             │ —                          │
 * │ Region Bounty Breakdown                        │ region-bounty-table        │ All / Alive Only           │
 * │ Saga Pacing Comparison                         │ saga-pacing                │ —                          │
 * │ Top 10 Highest Bounties                        │ top-bounties               │ All / Alive Only           │
 * │ Top Characters per Arc                         │ top-characters-per-arc     │ SHP 3-way + Count / %      │
 * │ Top Characters per Saga                        │ top-characters-per-saga    │ SHP 3-way + Count / %      │
 * │ Top Volume Cover Stars                         │ cover-stars                │ —                          │
 * │ Volume Cover vs Main Story Appearances         │ cover-vs-main              │ —                          │
 * └────────────────────────────────────────────────┴────────────────────────────┴────────────────────────────┘
 *
 * To add a new embed:
 * 1. Add the compute function call in the `insights` useMemo block
 * 2. Create an Embed* component in src/components/insights/Embed*Charts.tsx
 * 3. Add the slug → component mapping in `chartMap`
 * 4. Add chartId and embedPath props to the ChartCard in the relevant insight section
 *
 * Auto-generated by: npx tsx src/scripts/updateEmbedChartIndex.ts
 */
import { useMemo } from 'react'
import { useParams } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import {
  fetchInsightsRawData,
  computeChapterComplexity,
  computeBountyVsAppearance,
  computeTopBountyJumps,
  computeRegionBountyTier,
  computeMostLoyal,
  computeArcCountDistribution,
  computeSagaCountDistribution,
  computeArcIntroRate,
  computeSagaIntroRate,
  computeLongestGaps,
  computeSagaPacing,
  computeBloodTypeDistribution,
  computeRegionCounts,
  computeAgeDistribution,
  computeCoverStars,
  computeCoverVsMain,
  computeTopCharactersPerSaga,
  computeTopCharactersPerArc,
  computeLargestGroups,
  computeCrewLoyalty,
} from '../services/analyticsService'
import {
  EmbedCastComplexity,
  EmbedBountyVsAppearance,
  EmbedBountyJumps,
  EmbedRegionBountyTier,
  EmbedBountyDistribution,
  EmbedTopBounties,
  EmbedRegionBountyTable,
} from '../components/insights/EmbedBountyCharts'
import {
  EmbedMostLoyal,
  EmbedWondersDistribution,
  EmbedArcIntroRate,
  EmbedSagaIntroRate,
  EmbedGapAnalysis,
} from '../components/insights/EmbedAppearancesCharts'
import { EmbedSagaPacing } from '../components/insights/EmbedStoryCharts'
import {
  EmbedBloodTypeComparison,
  EmbedOriginRegions,
  EmbedAgeDistribution,
} from '../components/insights/EmbedDemographicsCharts'
import {
  EmbedCoverStars,
  EmbedCoverVsMain,
} from '../components/insights/EmbedCoverMetaCharts'
import {
  EmbedTopCharactersPerSaga,
  EmbedTopCharactersPerArc,
} from '../components/insights/EmbedRankingsCharts'
import {
  EmbedLargestGroups,
  EmbedCrewLoyalty,
} from '../components/insights/EmbedAffiliationsCharts'

function EmbedInsightPage() {
  const { chartId } = useParams<{ chartId: string }>()

  const { data: raw, isLoading } = useQuery({
    queryKey: ['insights-raw-data'],
    queryFn: fetchInsightsRawData,
    staleTime: 10 * 60 * 1000,
  })

  const insights = useMemo(() => {
    if (!raw) return null
    const { characters, arcs, sagas, chapters } = raw
    return {
      chapterComplexity: computeChapterComplexity(
        characters,
        arcs,
        chapters.length > 0 ? Math.max(...chapters.map((c) => c.number)) : 0
      ),
      bountyVsAppearance: computeBountyVsAppearance(characters),
      topBountyJumps: computeTopBountyJumps(characters),
      regionBountyTier: computeRegionBountyTier(characters),
      mostLoyal: computeMostLoyal(characters),
      arcCountDistribution: computeArcCountDistribution(characters, arcs, 2),
      sagaCountDistribution: computeSagaCountDistribution(characters, sagas, 2),
      arcIntroRate: computeArcIntroRate(characters, arcs),
      sagaIntroRate: computeSagaIntroRate(characters, sagas),
      longestGaps: computeLongestGaps(characters),
      sagaPacing: computeSagaPacing(sagas, arcs, characters, chapters),
      bloodType: computeBloodTypeDistribution(characters),
      regionCounts: computeRegionCounts(characters),
      ageDistribution: computeAgeDistribution(characters),
      coverStars: computeCoverStars(characters),
      coverVsMain: computeCoverVsMain(characters),
      topCharactersPerSaga: computeTopCharactersPerSaga(characters, sagas, 31),
      topCharactersPerArc: computeTopCharactersPerArc(characters, arcs, 31),
      largestGroups: computeLargestGroups(raw.affiliations),
      crewLoyalty: computeCrewLoyalty(raw.affiliations),
    }
  }, [raw])

  if (isLoading) {
    return (
      <div className="flex justify-center items-center p-8">
        <div className="animate-spin rounded-full h-10 w-10 border-b-2 border-blue-600"></div>
      </div>
    )
  }

  if (!insights) return null

  const chartMap: Record<string, React.ReactNode> = {
    'cast-complexity': (
      <EmbedCastComplexity data={insights.chapterComplexity} />
    ),
    'bounty-vs-appearance': (
      <EmbedBountyVsAppearance data={insights.bountyVsAppearance} />
    ),
    'bounty-jumps': <EmbedBountyJumps data={insights.topBountyJumps} />,
    'bounty-distribution': <EmbedBountyDistribution />,
    'top-bounties': <EmbedTopBounties />,
    'region-bounty-table': <EmbedRegionBountyTable />,
    'region-bounty-tier': (
      <EmbedRegionBountyTier data={insights.regionBountyTier.slice(0, 15)} />
    ),
    'most-loyal': <EmbedMostLoyal data={insights.mostLoyal} />,
    'wonders-distribution': (
      <EmbedWondersDistribution
        arcData={insights.arcCountDistribution}
        sagaData={insights.sagaCountDistribution}
      />
    ),
    'arc-intro-rate': <EmbedArcIntroRate data={insights.arcIntroRate} />,
    'saga-intro-rate': <EmbedSagaIntroRate data={insights.sagaIntroRate} />,
    'gap-analysis': <EmbedGapAnalysis data={insights.longestGaps} />,
    'saga-pacing': <EmbedSagaPacing data={insights.sagaPacing} />,
    'blood-type-comparison': (
      <EmbedBloodTypeComparison data={insights.bloodType} />
    ),
    'origin-regions': <EmbedOriginRegions data={insights.regionCounts} />,
    'age-distribution': (
      <EmbedAgeDistribution data={insights.ageDistribution} />
    ),
    'cover-stars': <EmbedCoverStars data={insights.coverStars} />,
    'cover-vs-main': <EmbedCoverVsMain data={insights.coverVsMain} />,
    'top-characters-per-saga': (
      <EmbedTopCharactersPerSaga data={insights.topCharactersPerSaga} />
    ),
    'top-characters-per-arc': (
      <EmbedTopCharactersPerArc data={insights.topCharactersPerArc} />
    ),
    'largest-groups': <EmbedLargestGroups data={insights.largestGroups} />,
    'crew-loyalty': <EmbedCrewLoyalty data={insights.crewLoyalty} />,
  }

  const chart = chartId ? chartMap[chartId] : null

  if (!chart) {
    return (
      <div className="p-8 text-center text-gray-500">
        Chart not found: {chartId}
      </div>
    )
  }

  return <>{chart}</>
}

export default EmbedInsightPage
