/**
 * Embed renderers for all insight charts.
 *
 * Each chart is accessible at: /#/embed/insights/<slug>
 * Permalink on the main page:  /#/analytics/insights#<slug>
 *
 * ┌─────┬────────────────────────────────────────┬────────────────────────────┬────────────────────────────┐
 * │ #   │ Title                                  │ Slug                       │ Interactive Filters        │
 * ├─────┼────────────────────────────────────────┼────────────────────────────┼────────────────────────────┤
 * │ 1   │ Cast Complexity Over Time              │ cast-complexity            │ —                          │
 * │ 2   │ Bounty vs Appearance Count             │ bounty-vs-appearance       │ SHP toggle                 │
 * │ 3   │ Bounty Jumps                           │ bounty-jumps               │ Sortable table             │
 * │ 4   │ Bounty Tier Distribution by Region     │ region-bounty-tier         │ Count / %                  │
 * │ 5   │ Most "Loyal" Characters                │ most-loyal                 │ —                          │
 * │ 6   │ One-Arc Wonders vs Recurring Cast      │ arc-count-distribution     │ —                          │
 * │ 6b  │ One-Saga Wonders vs Recurring Cast     │ saga-count-distribution    │ —                          │
 * │ 7   │ Characters per Arc (New vs Returning)  │ arc-intro-rate             │ Both / New / Returning     │
 * │ 7b  │ Characters per Saga (New vs Returning) │ saga-intro-rate            │ Both / New / Returning     │
 * │ 8   │ Longest Disappearances                 │ gap-analysis               │ Sortable table             │
 * │ 9   │ Arc Length Trend                       │ arc-length-trend           │ —                          │
 * │ 10  │ Total Pages per Arc                    │ pages-per-arc              │ —                          │
 * │ 11  │ Saga Pacing Comparison                 │ saga-pacing                │ —                          │
 * │ 12  │ Chapters per Year                      │ yearly-releases            │ —                          │
 * │ 13  │ Blood Type: One Piece vs Japan         │ blood-type-comparison      │ —                          │
 * │ 14  │ Birthday Calendar by Month             │ birthday-distribution      │ —                          │
 * │ 15  │ Origin Region Bubble Chart             │ origin-regions             │ —                          │
 * │ 16  │ Age Distribution by Status             │ age-distribution           │ —                          │
 * │ 17  │ Cover Page Stars                       │ cover-stars                │ —                          │
 * │ 18  │ Cover vs Main Story Appearances        │ cover-vs-main              │ —                          │
 * │ 19  │ Character Cast Size per Arc            │ arc-density                │ —                          │
 * │ 20  │ The Completeness Gap                   │ data-completeness          │ —                          │
 * │ 21  │ Top Characters per Saga                │ top-characters-per-saga    │ SHP 3-way + Count / %      │
 * │ 22  │ Top Characters per Arc                 │ top-characters-per-arc     │ SHP 3-way + Count / %      │
 * │ 23  │ Largest Crews & Organizations          │ largest-groups             │ —                          │
 * │ 24  │ Crew Loyalty vs Turnover               │ crew-loyalty               │ —                          │
 * └─────┴────────────────────────────────────────┴────────────────────────────┴────────────────────────────┘
 *
 * To add a new embed:
 * 1. Add the compute function call in the `insights` useMemo block
 * 2. Create an Embed* component in src/components/insights/Embed*Charts.tsx
 * 3. Add the slug → component mapping in `chartMap`
 * 4. Add chartId and embedPath props to the ChartCard on OnePieceInsightsPage
 *
 * Auto-generated by: npx tsx src/scripts/updateEmbedChartIndex.ts
 */
import { useMemo } from 'react'
import { useParams } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import {
  fetchInsightsRawData,
  computeChapterComplexity,
  computeBountyVsAppearance,
  computeTopBountyJumps,
  computeRegionBountyTier,
  computeMostLoyal,
  computeArcCountDistribution,
  computeSagaCountDistribution,
  computeArcIntroRate,
  computeSagaIntroRate,
  computeLongestGaps,
  computeArcLengths,
  computePagesPerArc,
  computeSagaPacing,
  computeYearlyReleases,
  computeBloodTypeComparison,
  computeBirthdayDistribution,
  computeRegionCounts,
  computeAgeDistribution,
  computeCoverStars,
  computeCoverVsMain,
  computeArcDensity,
  computeCompleteness,
  computeTopCharactersPerSaga,
  computeTopCharactersPerArc,
  computeLargestGroups,
  computeCrewLoyalty,
} from '../services/analyticsService'
import {
  EmbedCastComplexity,
  EmbedBountyVsAppearance,
  EmbedBountyJumps,
  EmbedRegionBountyTier,
} from '../components/insights/EmbedBountyCharts'
import {
  EmbedMostLoyal,
  EmbedArcCountDistribution,
  EmbedSagaCountDistribution,
  EmbedArcIntroRate,
  EmbedSagaIntroRate,
  EmbedGapAnalysis,
} from '../components/insights/EmbedAppearancesCharts'
import {
  EmbedArcLengthTrend,
  EmbedPagesPerArc,
  EmbedSagaPacing,
  EmbedYearlyReleases,
} from '../components/insights/EmbedStoryCharts'
import {
  EmbedBloodTypeComparison,
  EmbedBirthdayDistribution,
  EmbedOriginRegions,
  EmbedAgeDistribution,
} from '../components/insights/EmbedDemographicsCharts'
import {
  EmbedCoverStars,
  EmbedCoverVsMain,
  EmbedArcDensity,
  EmbedDataCompleteness,
} from '../components/insights/EmbedCoverMetaCharts'
import {
  EmbedTopCharactersPerSaga,
  EmbedTopCharactersPerArc,
} from '../components/insights/EmbedRankingsCharts'
import {
  EmbedLargestGroups,
  EmbedCrewLoyalty,
} from '../components/insights/EmbedAffiliationsCharts'

function EmbedInsightPage() {
  const { chartId } = useParams<{ chartId: string }>()

  const { data: raw, isLoading } = useQuery({
    queryKey: ['insights-raw-data'],
    queryFn: fetchInsightsRawData,
    staleTime: 10 * 60 * 1000,
  })

  const insights = useMemo(() => {
    if (!raw) return null
    const { characters, arcs, sagas, chapters } = raw
    return {
      chapterComplexity: computeChapterComplexity(
        characters,
        arcs,
        chapters.length > 0 ? Math.max(...chapters.map((c) => c.number)) : 0
      ),
      bountyVsAppearance: computeBountyVsAppearance(characters),
      topBountyJumps: computeTopBountyJumps(characters),
      regionBountyTier: computeRegionBountyTier(characters),
      mostLoyal: computeMostLoyal(characters),
      arcCountDistribution: computeArcCountDistribution(characters, arcs, 2),
      sagaCountDistribution: computeSagaCountDistribution(characters, sagas, 2),
      arcIntroRate: computeArcIntroRate(characters, arcs),
      sagaIntroRate: computeSagaIntroRate(characters, sagas),
      longestGaps: computeLongestGaps(characters),
      arcLengths: computeArcLengths(arcs),
      pagesPerArc: computePagesPerArc(arcs, chapters),
      sagaPacing: computeSagaPacing(sagas, arcs, characters, chapters),
      yearlyReleases: computeYearlyReleases(chapters),
      bloodType: computeBloodTypeComparison(characters),
      birthdays: computeBirthdayDistribution(characters),
      regionCounts: computeRegionCounts(characters),
      ageDistribution: computeAgeDistribution(characters),
      coverStars: computeCoverStars(characters),
      coverVsMain: computeCoverVsMain(characters),
      arcDensity: computeArcDensity(characters, arcs),
      completeness: computeCompleteness(characters),
      topCharactersPerSaga: computeTopCharactersPerSaga(characters, sagas, 31),
      topCharactersPerArc: computeTopCharactersPerArc(characters, arcs, 31),
      largestGroups: computeLargestGroups(raw.affiliations),
      crewLoyalty: computeCrewLoyalty(raw.affiliations),
    }
  }, [raw])

  if (isLoading) {
    return (
      <div className="flex justify-center items-center p-8">
        <div className="animate-spin rounded-full h-10 w-10 border-b-2 border-blue-600"></div>
      </div>
    )
  }

  if (!insights) return null

  const chartMap: Record<string, React.ReactNode> = {
    'cast-complexity': (
      <EmbedCastComplexity data={insights.chapterComplexity} />
    ),
    'bounty-vs-appearance': (
      <EmbedBountyVsAppearance data={insights.bountyVsAppearance} />
    ),
    'bounty-jumps': <EmbedBountyJumps data={insights.topBountyJumps} />,
    'region-bounty-tier': (
      <EmbedRegionBountyTier data={insights.regionBountyTier.slice(0, 15)} />
    ),
    'most-loyal': <EmbedMostLoyal data={insights.mostLoyal} />,
    'arc-count-distribution': (
      <EmbedArcCountDistribution data={insights.arcCountDistribution} />
    ),
    'saga-count-distribution': (
      <EmbedSagaCountDistribution data={insights.sagaCountDistribution} />
    ),
    'arc-intro-rate': <EmbedArcIntroRate data={insights.arcIntroRate} />,
    'saga-intro-rate': <EmbedSagaIntroRate data={insights.sagaIntroRate} />,
    'gap-analysis': <EmbedGapAnalysis data={insights.longestGaps} />,
    'arc-length-trend': <EmbedArcLengthTrend data={insights.arcLengths} />,
    'pages-per-arc': <EmbedPagesPerArc data={insights.pagesPerArc} />,
    'saga-pacing': <EmbedSagaPacing data={insights.sagaPacing} />,
    'yearly-releases': <EmbedYearlyReleases data={insights.yearlyReleases} />,
    'blood-type-comparison': (
      <EmbedBloodTypeComparison data={insights.bloodType} />
    ),
    'birthday-distribution': (
      <EmbedBirthdayDistribution data={insights.birthdays} />
    ),
    'origin-regions': <EmbedOriginRegions data={insights.regionCounts} />,
    'age-distribution': (
      <EmbedAgeDistribution data={insights.ageDistribution} />
    ),
    'cover-stars': <EmbedCoverStars data={insights.coverStars} />,
    'cover-vs-main': <EmbedCoverVsMain data={insights.coverVsMain} />,
    'arc-density': <EmbedArcDensity data={insights.arcDensity} />,
    'data-completeness': <EmbedDataCompleteness data={insights.completeness} />,
    'top-characters-per-saga': (
      <EmbedTopCharactersPerSaga data={insights.topCharactersPerSaga} />
    ),
    'top-characters-per-arc': (
      <EmbedTopCharactersPerArc data={insights.topCharactersPerArc} />
    ),
    'largest-groups': <EmbedLargestGroups data={insights.largestGroups} />,
    'crew-loyalty': <EmbedCrewLoyalty data={insights.crewLoyalty} />,
  }

  const chart = chartId ? chartMap[chartId] : null

  if (!chart) {
    return (
      <div className="p-8 text-center text-gray-500">
        Chart not found: {chartId}
      </div>
    )
  }

  return <>{chart}</>
}

export default EmbedInsightPage
